version: '3'
services:

  back:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/back
    container_name: back_dev
    ports:
      - '8000:8000'
    command: python run.py
    env_file:
      - ./env
